# Data Manipulation


In order to train neural networks, we first need to store and manipulate datasets.
So let us generate synthetic datasets and store them in a $n$-dimensional array, which is also called the *tensor*.

NumPy is the most widely-used scientific computing package in Python. it uses `ndarray` to store and manipulate tabular data (or matrices). 

No matter which framework you use, the *tensor class* (`ndarray` in MXNet,
`Tensor` in both PyTorch and TensorFlow) is similar to NumPy's `ndarray` with
additional features.

First, the *tensor class* in TensorFlow supports GPU to accelerate the computation
whereas NumPy only supports CPU computation.
Second, the *tensor class* supports automatic differentiation.

These properties make the *tensor class* suitable for deep learning. In this course, we refer to tensors as instances of the tensor class unless otherwise stated.

## Getting Started

The following sections will revisit the mathematical concepts of this lesson iwith practical examples in Python and TensorFlow. You will learn how the basic math and numerical computing are easily implemented with library functions that you will build on as you progress through the course.

To start, we import `tensorflow`. 

As the name is a little long, we often import
it with a short alias `tf`.


In [3]:
import tensorflow as tf

Definition:
> A tensor represents a (possibly multi-dimensional) array of numerical values.

- A tensor with  one axis corresponds (in math) to a *vector*.
- A tensor with  two axes corresponds to a *matrix*.
- Tensors with more than two axes do not have special mathematical names.

To start, we can use `arange` to create a row vector `x`
containing the first 12 integers starting with 0,
though they are created as floats by default.


In [4]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

Each of the values in the tensor is called an *element* of the tensor.

For instance, there are 12 elements in the tensor `x`.

Unless otherwise specified, a new tensor
will be stored in main memory and designated for CPU-based computation.



Let us access a tensor's *shape* which designates the length along each axis
To do so, we call the `shape` property.

In [5]:
x.shape

TensorShape([12])

If we just want to know the total number of elements in a tensor,
i.e., the product of all of the shape elements,we can inspect its size.

Since our vector x has a single element, its `shape` is identical to its size.


In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

To **change the shape of a tensor without altering
either the number of elements or their values**,
we can invoke the `reshape` function.

In [7]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In this example, we  transform our tensor, `x`, from a row vector with shape (12,) to a matrix with shape (3, 4).

This new tensor contains the exact same values, but views them as a matrix organized as 3 rows and 4 columns.

To reiterate, although the shape has changed, the elements have not.
Note that the size is unaltered by reshaping.

Reshaping by manually specifying every dimension is unnecessary.
If our target shape is a matrix with shape (`height`, `width`),
then after we know the width, the height is given implicitly.

Why should we have to perform the division ourselves?
In the example above, to get a matrix with 3 rows,
we specified both that it should have 3 rows and 4 columns.
Fortunately, tensors can automatically work out one dimension given the rest.
We invoke this capability by placing `-1` for the dimension
that we would like tensors to automatically infer.

In our case, instead of calling `x.reshape(3, 4)`,
we could have equivalently called `x.reshape(-1, 4)` or `x.reshape(3, -1)`.

Typically, we will want our matrices initialized
either with zeros, ones, some other constants,
or numbers randomly sampled from a specific distribution.
*We can create a tensor representing a tensor with all elements
set to 0* and a shape of (2, 3, 4) as follows:

In [8]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

Similarly, we can create tensors with each element set to 1 as follows:


In [9]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

Often, we want to *randomly sample the values
for each element in a tensor** from some probability distribution.

For example, when we construct arrays to serve
as parameters in a neural network, we will
typically initialize their values randomly.

In [10]:
tf.random.normal(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.29266113,  0.616908  , -0.5854539 ,  0.6873052 ],
       [-0.61713433, -1.8821822 ,  0.9895492 , -0.7166444 ],
       [-0.2591582 ,  0.3229179 , -1.1914335 ,  0.19949503]],
      dtype=float32)>

This snippet creates a tensor with shape (3, 4).

Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.

We can also [**specify the exact values for each element**] in the desired tensor
by supplying a Python list (or list of lists) containing the numerical values.

Here, the outermost list corresponds to axis 0, and the inner list to axis 1.


In [11]:
tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

## Elementwise Operations

In deep learning we not only read and write data from/to arrays. we also perform mathematical operations on those arrays.

**Elementwise operations:**

Some of the simplest and most useful operations
are the *elementwise* operations.
These apply a standard scalar operation
to each element of an array.
For functions that take two arrays as inputs,
elementwise operations apply some standard binary operator
on each pair of corresponding elements from the two arrays.
We can create an elementwise function from any function
that maps from a scalar to a scalar.

- *unary* scalar operator
    - In mathematical notation, we denote a *unary* scalar operator (taking one input)by the signature $f: \mathbb{R} \rightarrow \mathbb{R}$. This just means that the function is mapping
from any real number ($\mathbb{R}$) onto another.

- *binary* scalar operator:
    - We denote a *binary* scalar operator (taking two real inputs, and yielding one output) by the signature $f: \mathbb{R}, \mathbb{R} \rightarrow \mathbb{R}$.
Given any two vectors $\mathbf{u}$ and $\mathbf{v}$ *of the same shape*,
and a binary operator $f$, we can produce a vector
$\mathbf{c} = F(\mathbf{u},\mathbf{v})$
by setting $c_i \gets f(u_i, v_i)$ for all $i$,
where $c_i, u_i$, and $v_i$ are the $i^\mathrm{th}$ elements
of vectors $\mathbf{c}, \mathbf{u}$, and $\mathbf{v}$.
Here, we produced the vector-valued
$F: \mathbb{R}^d, \mathbb{R}^d \rightarrow \mathbb{R}^d$
by *lifting* the scalar function to an elementwise vector operation.

**Arithmetic operators**

- The common standard arithmetic operators
(`+`, `-`, `*`, `/`, and `**`)
have all been *lifted* to elementwise operations for any identically-shaped tensors of arbitrary shape.

- We can call elementwise operations on any two tensors of the same shape.
In the following example, we use commas to formulate a 5-element tuple,
where each element is the result of an elementwise operation.

***Elementwise Operations***

The common standard arithmetic operators
(`+`, `-`, `*`, `/`, and `**`)
have all been *lifted* to elementwise operations.

In [12]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  # The ** operator is exponentiation

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

Many (**more operations can be applied elementwise**),
including unary operators like exponentiation.


In [13]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

## Linear Algebra operations
In addition to elementwise computations,
- we can also perform linear algebra operations, including `vector dot products` and `matrix multiplication`.


- We can also concatenate multiple tensors together, stacking them end-to-end to form a larger tensor. We just need to provide a list of tensors
and tell the system along which axis to concatenate.

The example below shows what happens when we concatenate
two matrices along rows (axis 0, the first element of the shape)
vs. columns (axis 1, the second element of the shape).

We can see that the first output tensor's axis-0 length ($6$)
is the sum of the two input tensors' axis-0 lengths ($3 + 3$);
while the second output tensor's axis-1 length ($8$) is the sum of the two input tensors' axis-1 lengths ($4 + 4$).

In [14]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

Sometimes, we want to construct a binary tensor via *logical statements*.


Take `X == Y` as an example.

For each position, if `X` and `Y` are equal at that position,
the corresponding entry in the new tensor takes a value of 1,
meaning that the logical statement `X == Y` is true at that position;
otherwise that position takes 0.


In [15]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

Summing all the elements in the tensor yields a tensor with only one element.


In [16]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

## Broadcasting Mechanism


In the previous section, we performed elementwise operations
on two tensors of the same shape.

Under certain conditions, even when shapes differ, we can still perform elementwise operations by invoking the *broadcasting mechanism*.

This mechanism works in the following way:
- First, expand one or both arrays
by copying elements appropriately
so that after this transformation,
the two tensors have the same shape.
- Second, carry out the elementwise operations
on the resulting arrays.

In most cases, we broadcast along an axis where an array
initially only has length 1, such as in the following example:


In [17]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

Since `a` and `b` are $3\times1$ and $1\times2$ matrices respectively,
their shapes do not match up if we want to add them.
We *broadcast* the entries of both matrices into a larger $3\times2$ matrix as follows:
for matrix `a` it replicates the columns
and for matrix `b` it replicates the rows
before adding up both elementwise.


In [18]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

## Indexing and Slicing

Just as in any other Python array, elements in a tensor can be accessed by index.
As in any Python array, the first element has index 0 and ranges are specified to include the first but *before* the last element.


As in standard Python lists, we can access elements
according to their relative position to the end of the list
by using negative indices.

Thus, `[-1]` selects the last element and `[1:3]`
selects the second and the third elements as follows:

In [19]:
X[-1], X[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

`Tensors` in TensorFlow are immutable, and cannot be assigned to.

`Variables` in TensorFlow are mutable containers of state that support
assignments. Keep in mind that gradients in TensorFlow do not flow backwards
through `Variable` assignments.

Beyond assigning a value to the entire `Variable`, we can write elements of a
`Variable` by specifying indices.


In [20]:
X_var = tf.Variable(X)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

If we want to assign multiple elements the same value,
we simply index all of them and then assign them the value.

For instance, `[0:2, :]` accesses the first and second rows,
where `:` takes all the elements along axis 1 (column).

While we discussed indexing for matrices,
this obviously also works for vectors
and for tensors of more than 2 dimensions.

In [21]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2, :].shape, dtype=tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## Saving Memory

Running operations can cause new memory to be
allocated to host results.


For example, if we write `Y = X + Y`,
we will dereference the tensor that `Y` used to point to
and instead point `Y` at the newly allocated memory.

In the following example, we demonstrate this with Python's `id()` function,
which gives us the exact address of the referenced object in memory.

After running `Y = Y + X`, we will find that `id(Y)` points to a different location.
That is because Python first evaluates `Y + X`,
allocating new memory for the result and then makes `Y`
point to this new location in memory.

In [22]:
before = id(Y)
Y = Y + X
id(Y) == before

False

This might be undesirable for two reasons:
- First, we do not want to run around
allocating memory unnecessarily all the time.
In machine learning, we might have
hundreds of megabytes of parameters
and update all of them multiple times per second.
Typically, we will want to perform these updates *in place*.
- Second, we might point at the same parameters from multiple variables.
If we do not update in place, other references will still point to
the old memory location, making it possible for parts of our code
to inadvertently reference stale parameters.


`Variables` are mutable containers of state in TensorFlow. They provide
a way to store your model parameters.
We can assign the result of an operation
to a `Variable` with `assign`.

To illustrate this concept, we create a `Variable` `Z`
with the same shape as another tensor `Y`,
using `zeros_like` to allocate a block of $0$ entries.

In [23]:
Z = tf.Variable(tf.zeros_like(Y))
print('id(Z):', id(Z))
Z.assign(X + Y)
print('id(Z):', id(Z))

id(Z): 2330837854048
id(Z): 2330837854048


Even once you store state persistently in a `Variable`, you
may want to reduce your memory usage further by avoiding excess
allocations for tensors that are not your model parameters.

Because TensorFlow `Tensors` are immutable and gradients do not flow through
`Variable` assignments, TensorFlow does not provide an explicit way to run
an individual operation in-place.

However, TensorFlow provides the `tf.function` decorator to wrap computation
inside of a TensorFlow graph that gets compiled and optimized before running.
This allows TensorFlow to prune unused values, and to re-use
prior allocations that are no longer needed. This minimizes the memory
overhead of TensorFlow computations.


In [24]:
@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # This unused value will be pruned out
    A = X + Y  # Allocations will be re-used when no longer needed
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  9., 26., 27.],
       [24., 33., 42., 51.],
       [56., 57., 58., 59.]], dtype=float32)>

## Conversion to Other Python Objects

**Converting to a NumPy tensor**, or vice versa, is easy.
The converted result does not share memory.

This minor inconvenience is actually quite important:
when you perform operations on the CPU or on GPUs,
you do not want to halt computation, waiting to see
whether the NumPy package of Python might want to be doing something else
with the same chunk of memory.


In [25]:
A = X.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

To **convert a size-1 tensor to a Python scalar**,
we can invoke the `item` function or Python's built-in functions.


In [26]:
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)

## Summary

* The main interface to store and manipulate data for deep learning is the tensor ($n$-dimensional array). It provides a variety of functionalities including basic mathematics operations, broadcasting, indexing, slicing, memory saving, and conversion to other Python objects.


## Exercises

1. Run the code in this section. Change the conditional statement `X == Y` in this section to `X < Y` or `X > Y`, and then see what kind of tensor you can get.
1. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?



**Acknowledgement:** This Jupyter Notebook is adapted from the dive into Deep Learning open-source book.
